### ISSUE TITLE
Add the ability to analyze operation amplifiers

### ISSUE THREAD

**Issue by ethanholz** [EnricoMiccoli/nodal#5]

**Comment by EnricoMiccoli** [comment]
Something that already works is modeling the opamp with a VCVS. 

Two new component types could be useful:

1. a modeled opamp, nothing more than a macro that generates the VCVS and the other necessary components
2. an ideal opamp, with a new case in the `build_coefficients()` function

**Comment by EnricoMiccoli** [comment]
I have begun development of option 1 in the `opamp` branch. For more information see the commit message at 48094b34c65147571090a9162b2accb6a3296d7e.

Before looking into option 2 I have to refactor [`build_coefficients()`](https://github.com/EnricoMiccoli/nodal/blob/805a4b050894e5e4d50e1eea3b2720b0d26a2a6f/nodal/nodal.py#L155).
